### ISSUE TITLE
Write Freely Blogs don't federate

### ISSUE THREAD

**Issue by PaulaToThePeople** [YunoHost-Apps/writefreely_ynh#92]
### Describe the bug

Write Freely blogs installed via Yunohost don't federate with Mastodon

### Context

Hardware: VPS bought online: Hetzner cloud cx21
YunoHost version: 4.2.4 (stable).
I have access to my server : through the webadmin
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no

### Steps to reproduce

1. Install WF
2. Create a blog
3. copy the blogs url or handle (@blog@writefreely.domain) (or try with @paula@write.wien.rocks)
4. paste it in the Mastodon search field and press enter

### Expected behavior

You should find the blog and be able to follow it
But instead you get a "503 remote data could not be fetched" error

**Comment by wioxjk** [comment]
Experiencing the same issue. 
Seems like the app in yunohost does not link itself correctly.

1. Go to the blog
2. Click the title in order to arrive to the direct URL for the specific blogpost
3. Notifce how you get redirected to htttps://blogs.your.domain/blogs.your.domain/name-of-the-post


This breaks sitemaps and federation.

**Comment by wioxjk** [comment]
Any updates to this?

**Comment by yalh76** [comment]
Maybe it comes from mastodon ...
I've tested from a mastodon_ynh, and it works ...
![image](https://user-images.githubusercontent.com/30271971/127753126-1ba4d508-f91d-4df9-9d7e-bfb2514d8834.png)
